default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: yes_or_no_development

test:
  <<: *default
  database: yes_or_no_test

production:
  <<: *default
  database: yes_or_no_production
  username: app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
